version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev # Use a dev-specific Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev # Run Next.js in dev mode